POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpsZW0iLCJpZCI6IjY1NzZkMzg4M2MzM2U3NDc4OGRjMTI0YiIsImlhdCI6MTcwMjQ1OTI4MCwiZXhwIjoxNzAyNDYyODgwfQ.r7A01LcAZzXsaKvJRk7fJyDEyuPyhpU3K0nnVUC6TPI

{
    "title": "Entäs nyt",
    "author": "Testi",
    "url": "hienohomma.jp",
    "likes": 3
}
